# SPDX-FileCopyrightText: 2023 Arthit Suriyawongkul <suriyawa@tcd.ie>
# SPDX-License-Identifier: MIT

__version__ = "0.2.dev2"
__stav_namespace__ = ""

from stav.eu.aia import TechnicalDocumentation, LogRecord

AI_PROVIDER = "AIProvider"
PREVIOUSLY_EXISTING_PROCESS_EVALUATION_DOCUMENTATION = (
    "PreviouslyExistingProcessEvaluationDocumentation"
)
TECHNICAL_DOCUMENTATION_OBLIGATION = "TechnicalDocumentationObligation"
BASELINE_PROCESS_DESCRIPTION = "BaselineProcessDescription"
INSTRUCTIONS_OF_USE = "InstructionsOfUse"
MAKING_AVAILABLE_ON_THE_MARKET = "MakingAvailableOnTheMarket"
MARKET_SURVEILLENCE_AUTHORITY = "MarketSurveillenceAuthority"
SYSTEM_GENERAL_DESCRIPTION = "SystemGeneralDescription"
CURRENT_AND_POTENTIAL_FUTURE_IMPACTS = "CurrentAndPotentialFutureImpacts"
TECHNICAL_DOCUMENTATION = "TechnicalDocumentation"
QUALITY_MANAGEMENT_SYSTEM_DOCUMENTATION_OBLIGATION = (
    "QualityManagementSystemDocumentationObligation"
)
PUTTING_INTO_SERVICE = "PuttingIntoService"
INTENDED_PURPOSES = "IntendedPurposes"
DATA_MINIMIZATION_PRACTICES = "DataMinimizationPractices"
PRIVACY_RISKS_AND_PRIVACY_MEASURES_EVALUATION_DOCUMENTATION = (
    "PrivacyRisksAndPrivacyMeasuresEvaluationDocumentation"
)
PLACING_ON_THE_MARKET = "PlacingOnTheMarket"
INSTALLATION_INSTRUCTIONS = "InstallationInstructions"
SYSTEM_EVALUATION_DOCUMENTATION = "SystemEvaluationDocumentation"
PREVIOUSLY_EXISTING_PROCESS_KNOWN_NEGATIVE_IMPACT_INFORMATION = (
    "PreviouslyExistingProcessKnownNegativeImpactInformation"
)
PREVIOUSLY_EXISTING_PROCESS_DOCUMENTATION = "PreviouslyExistingProcessDocumentation"
CONSUMER_RIGHTS_EVALUATION_INFORMATION = "ConsumerRightsEvaluationInformation"
INFORMATION_CREATION_OBLIGATION = "InformationCreationObligation"
AI_DEPLOYER = "AIDeployer"
IMPACT_ASSESSMENT_DOCUMENTATION = "ImpactAssessmentDocumentation"
INTENDED_BENEFITS_OVER_PREVIOUSLY_EXISTING_PROCESS = (
    "IntendedBenefitsOverPreviouslyExistingProcess"
)
INFORMATION_SUBMISSION_OBLIGATION = "InformationSubmissionObligation"
LOG = "Log"
INFORMATION_SECURITY_MEASURES = "InformationSecurityMeasures"
REGISTERATION_OBLIGATION = "RegisterationObligation"

METRICS_RECALL = "MetricsRecall"
METRICS_PRECISION = "MetricsPrecision"
METRICS_F1 = "MetricsF1"
METRICS_R2 = "MetricsR2"
METRICS_RMSE = "MetricsRMSE"
METRICS_MAE = "MetricsMAE"

METRICS_ENERGY = "MetricsEnergy"

DATASET_SIZE = "DatasetSize"

ENERY_CONSUMPTION = "EnergyConsumption"  # SPDX AI Profile
AUTONOMY_TYPE = "AutonomyType"  # SPDX AI Profile

__all__ = [
    TechnicalDocumentation,
    LogRecord,
    "AI_PROVIDER",
    "PREVIOUSLY_EXISTING_PROCESS_EVALUATION_DOCUMENTATION",
    "TECHNICAL_DOCUMENTATION_OBLIGATION",
    "BASELINE_PROCESS_DESCRIPTION",
    "INSTRUCTIONS_OF_USE",
    "MAKING_AVAILABLE_ON_THE_MARKET",
    "MARKET_SURVEILLENCE_AUTHORITY",
    "SYSTEM_GENERAL_DESCRIPTION",
    "CURRENT_AND_POTENTIAL_FUTURE_IMPACTS",
    "TECHNICAL_DOCUMENTATION",
    "QUALITY_MANAGEMENT_SYSTEM_DOCUMENTATION_OBLIGATION",
    "PUTTING_INTO_SERVICE",
    "INTENDED_PURPOSES",
    "DATA_MINIMIZATION_PRACTICES",
    "PRIVACY_RISKS_AND_PRIVACY_MEASURES_EVALUATION_DOCUMENTATION",
    "PLACING_ON_THE_MARKET",
    "INSTALLATION_INSTRUCTIONS",
    "SYSTEM_EVALUATION_DOCUMENTATION",
    "PREVIOUSLY_EXISTING_PROCESS_KNOWN_NEGATIVE_IMPACT_INFORMATION",
    "PREVIOUSLY_EXISTING_PROCESS_DOCUMENTATION",
    "CONSUMER_RIGHTS_EVALUATION_INFORMATION",
    "INFORMATION_CREATION_OBLIGATION",
    "AI_DEPLOYER",
    "IMPACT_ASSESSMENT_DOCUMENTATION",
    "INTENDED_BENEFITS_OVER_PREVIOUSLY_EXISTING_PROCESS",
    "INFORMATION_SUBMISSION_OBLIGATION",
    "LOG",
    "INFORMATION_SECURITY_MEASURES",
    "REGISTERATION_OBLIGATION",
    "stav.eu.aia.TechnicalDocumentation",
    "stav.eu.aia.LogRecord",
    "METRICS_RECALL",
    "METRICS_PRECISION",
    "METRICS_F1",
    "METRICS_R2",
    "METRICS_RMSE",
    "METRICS_MAE",
    "METRICS_ENERGY",
    "DATASET_SIZE",
    "ENERY_CONSUMPTION",
    "AUTONOMY_TYPE",
]
